"""Phase 1 initial schema: users, farmers, fields, catalog, observations, provenance.

Hand-authored rather than autogenerated so that extension creation, native enum
creation and the spatial indexes are explicit and reviewable.

Revision ID: 0001_initial
Revises:
Create Date: Phase 1
"""

from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


ENUMS: dict[str, tuple[str, ...]] = {
    "user_role": ("FARMER", "EXTENSION_WORKER", "LAB_EXPERT", "OFFICIAL", "ADMIN"),
    "source_type": (
        "FIELD_OBSERVATION",
        "PUBLIC_DATA",
        "GOVERNMENT_DATA",
        "EXPERT_VALIDATION",
        "DEMO_SIMULATION",
    ),
    "verification_status": (
        "PREDICTED",
        "PENDING_REVIEW",
        "CONFIRMED",
        "CORRECTED",
        "REJECTED",
        "LAB_REFERRED",
    ),
    "observation_status": (
        "PROCESSING",
        "COMPLETED",
        "AI_FAILED",
        "UNSUPPORTED_IMAGE",
        "RISK_UNAVAILABLE",
    ),
    "observation_type": ("IMAGE", "PEST_TRAP", "SENSOR", "MANUAL_REPORT"),
    "agent_kind": ("DISEASE", "PEST", "DISORDER", "HEALTHY", "UNKNOWN"),
    "language_code": ("en", "hi", "mr"),
}


def _enum(name: str) -> postgresql.ENUM:
    """Reference an already-created type; never re-create it per column."""
    return postgresql.ENUM(*ENUMS[name], name=name, create_type=False)


def _point() -> geoalchemy2.Geometry:
    return geoalchemy2.Geometry(geometry_type="POINT", srid=4326, spatial_index=False)


def upgrade() -> None:
    # ---- extensions -----------------------------------------------------------
    # postgis: spatial types and functions. pgcrypto: gen_random_uuid() for PKs.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")

    # ---- native enum types ----------------------------------------------------
    for name, values in ENUMS.items():
        postgresql.ENUM(*values, name=name).create(op.get_bind(), checkfirst=True)

    # ---- admin_regions --------------------------------------------------------
    # Ships EMPTY. No boundary dataset has been selected or licence-verified
    # (TRD decision D7), so no boundary data is invented here.
    op.create_table(
        "admin_regions",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("code", sa.String(20), nullable=False),
        sa.Column("name", sa.String(150), nullable=False),
        sa.Column("level", sa.String(20), nullable=False),
        sa.Column("parent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("geom", geoalchemy2.Geometry(geometry_type="MULTIPOLYGON", srid=4326,
                                               spatial_index=False), nullable=True),
        sa.Column("source_type", _enum("source_type"), nullable=False),
        sa.Column("original_source_ref", sa.String(), nullable=True),
        sa.Column("source_reference", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_admin_regions_code"),
        sa.ForeignKeyConstraint(["parent_id"], ["admin_regions.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_admin_regions_level", "admin_regions", ["level"])
    op.create_index("ix_admin_regions_parent_id", "admin_regions", ["parent_id"])
    op.create_index("gix_admin_regions_geom", "admin_regions", ["geom"], postgresql_using="gist")

    # ---- users ----------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("phone", sa.String(20), nullable=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("username", sa.String(64), nullable=True),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("full_name", sa.String(150), nullable=False),
        sa.Column("role", _enum("user_role"), server_default="FARMER", nullable=False),
        sa.Column("preferred_language", _enum("language_code"), server_default="en",
                  nullable=False),
        sa.Column("district_code", sa.String(20), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("phone", name="uq_users_phone"),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("username", name="uq_users_username"),
        sa.CheckConstraint(
            "phone IS NOT NULL OR email IS NOT NULL OR username IS NOT NULL",
            name="ck_users_has_identifier",
        ),
        sa.ForeignKeyConstraint(["district_code"], ["admin_regions.code"], ondelete="SET NULL"),
    )
    op.create_index("ix_users_role", "users", ["role"])
    op.create_index("ix_users_district_code", "users", ["district_code"])

    # ---- refresh_tokens -------------------------------------------------------
    op.create_table(
        "refresh_tokens",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash", name="uq_refresh_tokens_hash"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_refresh_tokens_user_id", "refresh_tokens", ["user_id"])

    # ---- data_sources ---------------------------------------------------------
    op.create_table(
        "data_sources",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("code", sa.String(60), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("source_type", _enum("source_type"), nullable=False),
        sa.Column("category", sa.String(40), nullable=False),
        sa.Column("provider_name", sa.String(150), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("licence", sa.String(120), nullable=True),
        sa.Column("version_or_release", sa.String(60), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_verified", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("verified_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_data_sources_code"),
        sa.CheckConstraint(
            "category IN ('BOUNDARY','WEATHER','CROP_STATS','TRAINING_DATA',"
            "'ADVISORY_CONTENT','REFERENCE_CATALOG','OTHER')",
            name="ck_data_sources_category",
        ),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_data_sources_category", "data_sources", ["category"])

    # ---- crops / varieties / growth stages ------------------------------------
    op.create_table(
        "crops",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("code", sa.String(40), nullable=False),
        sa.Column("name_en", sa.String(120), nullable=False),
        sa.Column("name_hi", sa.String(120), nullable=False),
        sa.Column("name_mr", sa.String(120), nullable=False),
        sa.Column("scientific_name", sa.String(150), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_crops_code"),
    )

    op.create_table(
        "crop_varieties",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("crop_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(60), nullable=False),
        sa.Column("name_en", sa.String(120), nullable=False),
        sa.Column("name_hi", sa.String(120), nullable=False),
        sa.Column("name_mr", sa.String(120), nullable=False),
        sa.Column("duration_days", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crop_id", "code", name="uq_crop_varieties_crop_code"),
        sa.ForeignKeyConstraint(["crop_id"], ["crops.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_crop_varieties_crop_id", "crop_varieties", ["crop_id"])

    op.create_table(
        "growth_stages",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("crop_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("code", sa.String(40), nullable=False),
        sa.Column("name_en", sa.String(120), nullable=False),
        sa.Column("name_hi", sa.String(120), nullable=False),
        sa.Column("name_mr", sa.String(120), nullable=False),
        sa.Column("sequence", sa.SmallInteger(), nullable=False),
        sa.Column("typical_days_from_sowing_min", sa.Integer(), nullable=True),
        sa.Column("typical_days_from_sowing_max", sa.Integer(), nullable=True),
        sa.Column("susceptibility_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("crop_id", "code", name="uq_growth_stages_crop_code"),
        sa.UniqueConstraint("crop_id", "sequence", name="uq_growth_stages_crop_sequence"),
        sa.ForeignKeyConstraint(["crop_id"], ["crops.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_growth_stages_crop_id", "growth_stages", ["crop_id"])

    # ---- disease/pest catalogue ----------------------------------------------
    op.create_table(
        "disease_pest_catalog",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("code", sa.String(80), nullable=False),
        sa.Column("kind", _enum("agent_kind"), nullable=False),
        sa.Column("name_en", sa.String(150), nullable=False),
        sa.Column("name_hi", sa.String(150), nullable=False),
        sa.Column("name_mr", sa.String(150), nullable=False),
        sa.Column("scientific_name", sa.String(150), nullable=True),
        sa.Column("description_key", sa.String(120), nullable=True),
        # false until a registered model actually declares the class (Phase 2).
        sa.Column("is_ai_supported", sa.Boolean(), server_default=sa.text("false"),
                  nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_disease_pest_catalog_code"),
    )
    op.create_index("ix_disease_pest_catalog_kind", "disease_pest_catalog", ["kind"])

    op.create_table(
        "agent_crops",
        sa.Column("agent_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("crop_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.PrimaryKeyConstraint("agent_id", "crop_id"),
        sa.ForeignKeyConstraint(["agent_id"], ["disease_pest_catalog.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["crop_id"], ["crops.id"], ondelete="CASCADE"),
    )

    op.create_table(
        "symptoms",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("code", sa.String(60), nullable=False),
        sa.Column("name_en", sa.String(150), nullable=False),
        sa.Column("name_hi", sa.String(150), nullable=False),
        sa.Column("name_mr", sa.String(150), nullable=False),
        sa.Column("body_part", sa.String(40), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code", name="uq_symptoms_code"),
    )

    op.create_table(
        "agent_symptoms",
        sa.Column("agent_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("symptom_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("typicality", sa.SmallInteger(), nullable=True),
        sa.PrimaryKeyConstraint("agent_id", "symptom_id"),
        sa.ForeignKeyConstraint(["agent_id"], ["disease_pest_catalog.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["symptom_id"], ["symptoms.id"], ondelete="CASCADE"),
    )

    # ---- farmers --------------------------------------------------------------
    op.create_table(
        "farmers",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("village", sa.String(120), nullable=True),
        sa.Column("taluka", sa.String(120), nullable=True),
        sa.Column("district_code", sa.String(20), nullable=True),
        sa.Column("land_holding_ha", sa.Numeric(8, 2), nullable=True),
        sa.Column("primary_crop_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("research_consent", sa.Boolean(), server_default=sa.text("false"),
                  nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", name="uq_farmers_user_id"),
        sa.CheckConstraint("land_holding_ha IS NULL OR land_holding_ha >= 0",
                           name="ck_farmers_land_holding_non_negative"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["district_code"], ["admin_regions.code"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["primary_crop_id"], ["crops.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_farmers_district_code", "farmers", ["district_code"])

    # ---- fields ---------------------------------------------------------------
    op.create_table(
        "fields",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("farmer_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(120), nullable=False),
        sa.Column("centroid", _point(), nullable=False),
        sa.Column("boundary", geoalchemy2.Geometry(geometry_type="POLYGON", srid=4326,
                                                   spatial_index=False), nullable=True),
        sa.Column("area_ha", sa.Numeric(10, 3), nullable=True),
        sa.Column("soil_type", sa.String(60), nullable=True),
        sa.Column("irrigation_type", sa.String(60), nullable=True),
        sa.Column("district_code", sa.String(20), nullable=True),
        sa.Column("current_crop_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("current_variety_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("sowing_date", sa.Date(), nullable=True),
        sa.Column("created_by", postgresql.UUID(as_uuid=True), nullable=False),
        # Provenance: NOT NULL with no default, by design (TRD 10.2).
        sa.Column("source_type", _enum("source_type"), nullable=False),
        sa.Column("original_source_ref", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("farmer_id", "name", name="uq_fields_farmer_name"),
        sa.CheckConstraint("area_ha IS NULL OR area_ha > 0", name="ck_fields_area_positive"),
        sa.CheckConstraint("boundary IS NULL OR ST_IsValid(boundary)",
                           name="ck_fields_boundary_valid"),
        sa.CheckConstraint("boundary IS NULL OR ST_Contains(boundary, centroid)",
                           name="ck_fields_centroid_in_boundary"),
        sa.ForeignKeyConstraint(["farmer_id"], ["farmers.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["district_code"], ["admin_regions.code"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["current_crop_id"], ["crops.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["current_variety_id"], ["crop_varieties.id"],
                                ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_fields_farmer_id", "fields", ["farmer_id"])
    op.create_index("ix_fields_district_code", "fields", ["district_code"])
    op.create_index("gix_fields_centroid", "fields", ["centroid"], postgresql_using="gist")
    op.create_index("gix_fields_boundary", "fields", ["boundary"], postgresql_using="gist")

    # ---- observations ---------------------------------------------------------
    op.create_table(
        "observations",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("farmer_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("reported_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("field_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("crop_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("variety_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("growth_stage_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("observation_type", _enum("observation_type"), server_default="IMAGE",
                  nullable=False),
        sa.Column("latitude", sa.Numeric(9, 6), nullable=False),
        sa.Column("longitude", sa.Numeric(9, 6), nullable=False),
        sa.Column("geom", _point(), nullable=False),
        sa.Column("gps_accuracy_m", sa.Numeric(7, 2), nullable=True),
        sa.Column("location_method", sa.String(20), server_default="DEVICE_GPS", nullable=False),
        sa.Column("district_code", sa.String(20), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("reported_severity", sa.SmallInteger(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("status", _enum("observation_status"), server_default="PROCESSING",
                  nullable=False),
        sa.Column("verification_status", _enum("verification_status"), server_default="PREDICTED",
                  nullable=False),
        sa.Column("final_agent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("verified_by", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("source_type", _enum("source_type"), nullable=False),
        sa.Column("original_source_ref", sa.String(), nullable=True),
        sa.Column("data_source_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("parent_observation_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("processing_errors", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("latitude >= -90 AND latitude <= 90", name="ck_obs_latitude_range"),
        sa.CheckConstraint("longitude >= -180 AND longitude <= 180",
                           name="ck_obs_longitude_range"),
        sa.CheckConstraint("reported_severity IS NULL OR (reported_severity BETWEEN 1 AND 5)",
                           name="ck_obs_reported_severity_range"),
        sa.CheckConstraint("location_method IN ('DEVICE_GPS','MAP_PIN','FIELD_CENTROID')",
                           name="ck_obs_location_method"),
        # A prediction can never masquerade as a confirmed diagnosis.
        sa.CheckConstraint(
            "final_agent_id IS NULL OR verification_status IN ('CONFIRMED','CORRECTED')",
            name="ck_obs_final_agent_requires_verification",
        ),
        sa.ForeignKeyConstraint(["farmer_id"], ["farmers.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["reported_by"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["field_id"], ["fields.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["crop_id"], ["crops.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["variety_id"], ["crop_varieties.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["growth_stage_id"], ["growth_stages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["district_code"], ["admin_regions.code"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["final_agent_id"], ["disease_pest_catalog.id"],
                                ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["data_source_id"], ["data_sources.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_observation_id"], ["observations.id"],
                                ondelete="SET NULL"),
    )
    op.create_index("gix_observations_geom", "observations", ["geom"], postgresql_using="gist")
    op.create_index("ix_obs_observed_at", "observations", ["observed_at"])
    op.create_index("ix_obs_verification_status", "observations", ["verification_status"])
    op.create_index("ix_obs_source_type", "observations", ["source_type"])
    op.create_index("ix_obs_crop_id", "observations", ["crop_id"])
    op.create_index("ix_obs_field_id", "observations", ["field_id"])
    op.create_index("ix_obs_farmer_id", "observations", ["farmer_id"])
    op.create_index("ix_obs_district_code", "observations", ["district_code"])
    op.create_index("ix_obs_district_observed_at", "observations",
                    ["district_code", "observed_at"])
    op.create_index("ix_obs_status_verif", "observations", ["status", "verification_status"])
    op.create_index("ix_obs_parent", "observations", ["parent_observation_id"])

    # Partial spatial indexes for the two hottest map queries (TRD 9.3). Created now
    # so Phase 4 inherits them rather than needing a schema change.
    op.execute(
        "CREATE INDEX gix_obs_geom_confirmed ON observations USING GIST (geom) "
        "WHERE verification_status IN ('CONFIRMED','CORRECTED') AND deleted_at IS NULL"
    )
    op.execute(
        "CREATE INDEX gix_obs_geom_real ON observations USING GIST (geom) "
        "WHERE source_type <> 'DEMO_SIMULATION' AND deleted_at IS NULL"
    )

    # ---- observation_images ---------------------------------------------------
    op.create_table(
        "observation_images",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("observation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("thumbnail_key", sa.Text(), nullable=True),
        sa.Column("original_filename", sa.String(255), nullable=True),
        sa.Column("mime_type", sa.String(50), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("width_px", sa.Integer(), nullable=True),
        sa.Column("height_px", sa.Integer(), nullable=True),
        sa.Column("checksum_sha256", sa.String(64), nullable=False),
        sa.Column("exif_captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exif_latitude", sa.Numeric(9, 6), nullable=True),
        sa.Column("exif_longitude", sa.Numeric(9, 6), nullable=True),
        sa.Column("quality_flags", postgresql.JSONB(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("uploaded_by", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("size_bytes > 0", name="ck_obs_images_size_positive"),
        sa.ForeignKeyConstraint(["observation_id"], ["observations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["uploaded_by"], ["users.id"], ondelete="RESTRICT"),
    )
    op.create_index("ix_obs_images_observation_id", "observation_images", ["observation_id"])
    op.create_index("ix_obs_images_checksum", "observation_images", ["checksum_sha256"])

    # ---- AI registry and predictions -----------------------------------------
    # Created but EMPTY in Phase 1: no model is registered and no prediction exists.
    op.create_table(
        "ai_model_registry",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("model_version", sa.String(60), nullable=False),
        sa.Column("task", sa.String(30), nullable=False),
        sa.Column("framework", sa.String(30), nullable=False),
        sa.Column("runner_class", sa.String(120), nullable=False),
        sa.Column("artifact_key", sa.Text(), nullable=False),
        sa.Column("artifact_checksum", sa.String(64), nullable=False),
        sa.Column("input_size", sa.String(20), nullable=False),
        sa.Column("class_list", postgresql.JSONB(), nullable=False),
        sa.Column("high_confidence_threshold", sa.Numeric(4, 3), nullable=False),
        sa.Column("low_confidence_threshold", sa.Numeric(4, 3), nullable=False),
        sa.Column("training_dataset_ref", sa.Text(), nullable=True),
        # Never pre-filled: populated only from a real evaluation run.
        sa.Column("evaluation_metrics", postgresql.JSONB(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_version", name="uq_ai_model_registry_version"),
        sa.CheckConstraint("task IN ('CLASSIFICATION','DETECTION')", name="ck_model_task"),
        sa.CheckConstraint(
            "high_confidence_threshold >= 0 AND high_confidence_threshold <= 1 "
            "AND low_confidence_threshold >= 0 AND low_confidence_threshold <= 1 "
            "AND low_confidence_threshold <= high_confidence_threshold",
            name="ck_model_thresholds",
        ),
    )
    op.execute(
        "CREATE UNIQUE INDEX uq_active_model_per_task ON ai_model_registry (task) "
        "WHERE is_active"
    )

    op.create_table(
        "ai_predictions",
        sa.Column("id", postgresql.UUID(as_uuid=True), server_default=sa.text("gen_random_uuid()"),
                  nullable=False),
        sa.Column("observation_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("image_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("model_version", sa.String(60), nullable=False),
        sa.Column("predicted_agent_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("predicted_class", sa.String(80), nullable=False),
        sa.Column("confidence", sa.Numeric(5, 4), nullable=False),
        sa.Column("top_k", postgresql.JSONB(), nullable=True),
        sa.Column("severity_estimate", sa.Numeric(5, 4), nullable=True),
        sa.Column("is_low_confidence", sa.Boolean(), nullable=False),
        sa.Column("bbox_geojson", postgresql.JSONB(), nullable=True),
        sa.Column("inference_ms", sa.Integer(), nullable=True),
        sa.Column("runtime_device", sa.String(20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint("confidence >= 0 AND confidence <= 1",
                           name="ck_ai_pred_confidence_range"),
        sa.ForeignKeyConstraint(["observation_id"], ["observations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["image_id"], ["observation_images.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["model_version"], ["ai_model_registry.model_version"],
                                ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["predicted_agent_id"], ["disease_pest_catalog.id"],
                                ondelete="SET NULL"),
    )
    op.create_index("ix_ai_pred_observation_id", "ai_predictions", ["observation_id"])
    op.create_index("ix_ai_pred_model_version", "ai_predictions", ["model_version"])
    op.create_index("ix_ai_pred_confidence", "ai_predictions", ["confidence"])

    # ---- audit_logs -----------------------------------------------------------
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("actor_role", _enum("user_role"), nullable=True),
        sa.Column("action", sa.String(80), nullable=False),
        sa.Column("entity_type", sa.String(60), nullable=False),
        sa.Column("entity_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("before_state", postgresql.JSONB(), nullable=True),
        sa.Column("after_state", postgresql.JSONB(), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("trace_id", sa.String(64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"),
                  nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["actor_user_id"], ["users.id"], ondelete="SET NULL"),
    )
    op.create_index("ix_audit_entity", "audit_logs", ["entity_type", "entity_id"])
    op.create_index("ix_audit_actor_time", "audit_logs", ["actor_user_id", "created_at"])
    op.create_index("ix_audit_action_time", "audit_logs", ["action", "created_at"])


def downgrade() -> None:
    for table in (
        "audit_logs",
        "ai_predictions",
        "ai_model_registry",
        "observation_images",
        "observations",
        "fields",
        "farmers",
        "agent_symptoms",
        "symptoms",
        "agent_crops",
        "disease_pest_catalog",
        "growth_stages",
        "crop_varieties",
        "crops",
        "data_sources",
        "refresh_tokens",
        "users",
        "admin_regions",
    ):
        op.drop_table(table)

    for name in ENUMS:
        postgresql.ENUM(name=name).drop(op.get_bind(), checkfirst=True)

    # The postgis and pgcrypto extensions are intentionally NOT dropped: they may be
    # shared with other schemas in the same database.
